theme: jekyll-theme-cayman
title: Crona Virus ML model
description: Predicting the COVID-19 death rate in a country, according to it's characteristics || [Repo]({% post url https://github.com/Nohamika/Nohamika.github.io %})
url:  https://github.com/Nohamika/Nohamika.github.io
